[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
axum = "0.7.9"
axum-server = "0.7.1"
serde = "1.0.215"
serde_json = "1.0.133"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
wasmtime = "27.0.0"
